angler_catalog:
    resource: "@AnglerCatalogBundle/Resources/config/routing.yml"
    prefix:   /catalog

angler_test:
    resource: "@AnglerTestBundle/Resources/config/routing.yml"
    prefix:   /

angler_core:
    resource: "@AnglerCoreBundle/Resources/config/routing.yml"
    prefix:   /

angler_frontend:
    resource: "@AnglerFrontendBundle/Resources/config/routing.yml"
    prefix:   /

angler_backend:
    resource: "@AnglerBackendBundle/Resources/config/routing.yml"
    prefix:   /backend

angler_checkout:
    resource: "@AnglerCheckoutBundle/Resources/config/routing.yml"
    prefix:   /checkout

angler_user:
    resource: "@AnglerUserBundle/Resources/config/routing.yml"
    prefix:   /




# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
