AnglerCheckoutBundle:
    resource: "@AnglerCheckoutBundle/Resources/config/routing.yml"
    prefix:   /

AnglerBackendBundle:
    resource: "@AnglerBackendBundle/Resources/config/routing.yml"
    prefix:   /

AnglerFrontendBundle:
    resource: "@AnglerFrontendBundle/Resources/config/routing.yml"
    prefix:   /

AnglerCoreBundle:
    resource: "@AnglerCoreBundle/Resources/config/routing.php"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
