security:
    encoders:
        Angler\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: AnglerUserBundle:User, property: username }
#        in_memory:
#            users:
#                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
#        admin_area:
#            pattern: ^/backend/
#            http_basic: ~

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        login:
#            pattern:  ^/backend/login/$
#            security: true

        login:
            pattern:  ^/backend/login/$
            security: false

        secured_area:
            pattern:    ^/backend/
            form_login:
                check_path: /backend/login_check/
                login_path: /backend/login/
            logout:
                path:   /backend/logout/
                target: /backend/


    access_control:
        - { path: ^/backend/, roles: ROLE_ADMIN }
        - { path: ^/backend/login/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
