parameters:
#    angler_user.example.class: Angler\UserBundle\Example

services:
#    angler_user.example:
#        class: %angler_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
