parameters:
#    angler_core.example.class: Angler\CoreBundle\Example

services:
#    angler_core.example:
#        class: %angler_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
