parameters:
#    angler_checkout.example.class: Angler\CheckoutBundle\Example

services:
#    angler_checkout.example:
#        class: %angler_checkout.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
