angler_backend_login:
    pattern:  /login/
    defaults: { _controller: AnglerBackendBundle:Authentication:login }

angler_backend_login_check:
    pattern:  /login_check/


angler_backend_homepage:
    pattern:  /
    defaults: { _controller: AnglerBackendBundle:Default:index }

