parameters:
#    angler_backend.example.class: Angler\BackendBundle\Example

services:
#    angler_backend.example:
#        class: %angler_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
